// <auto-generated />
using System;
using AIFinanceAdvisor.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIFinanceAdvisor.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIFinanceAdvisor.Core.Entities.ChatHistoryForUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdConversation")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TopicMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChatHistoryForUsers", (string)null);
                });

            modelBuilder.Entity("AIFinanceAdvisor.Core.Entities.ChatMessageHistoryForAssitant", b =>
                {
                    b.Property<Guid>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdConverstation")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdMessage");

                    b.ToTable("ChatMessageHistoryForAssistants", (string)null);
                });

            modelBuilder.Entity("AIFinanceAdvisor.Core.Entities.ChatMessageHistoryForUser", b =>
                {
                    b.Property<Guid>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdConverstation")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdMessage");

                    b.ToTable("ChatMessageHistoryForUsers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
